[package]
name = "fm-tarpack"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
flate2 = "1.1.10"
fm-core = { path = "../fm-core" }
liblzma = { version = "0.4.8", features = ["static"] }
serde = { version = "1.0.229", features = ["derive"] }
sha2 = "0.11.0"
tar = { version = "0.4.46", default-features = false }
tempfile = { workspace = true }
toml = { version = "1.1.6", features = ["parse", "serde"] }
ts-rs = { workspace = true, features = ["no-serde-warnings"] }
zstd = "0.14.0"

[dev-dependencies]
serde_json = "1"
